#!/bin/bash

NAME="cuchanoble"                                   # Name of the application
DJANGODIR=/home/facundo/cuchanoble-backend               # Django project directory
SOCKFILE=/home/facundo/django_env/run/gunicorn.sock  # we will communicte using this unix socket
USER=facundo                                         # the user to run as
GROUP=sudo                                        # the group to run as
NUM_WORKERS=3                                       # how many worker processes should Gunicorn spawn
DJANGO_SETTINGS_MODULE=cuchanoble.settings      # which settings file should Django use
DJANGO_WSGI_MODULE=cuchanoble.wsgi              # WSGI module name
echo "Starting $NAME as `whoami`"

cd $DJANGODIR
source /home/facundo/django_env/bin/activate
export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DJANGODIR:$PYTHONPATH

RUNDIR=$(dirname $SOCKFILE)
test -d $RUNDIR || mkdir -p $RUNDIR

exec gunicorn ${DJANGO_WSGI_MODULE}:application \
  --name $NAME \
  --workers $NUM_WORKERS \
  --user=$USER --group=$GROUP \
  --bind=unix:$SOCKFILE \
  --log-level=debug \
  --log-file=-


/////////////////////////////////////////////
[program:cuchanoble]
command=/home/facundoalvarado9/cuchanoble-backend/bin/gunicorn_start
user=facundoalvarado9
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/home/facundoalvarado9/cuchanoble-backend/logs/gunicorn-error.log

[program:cuchanoble]
command = /home/facundo/DOfiles/gunicorn_start.bash                  ; Command to start app
user = facundo                                                ; User to run as
stdout_logfile = /home/facundo/logs/gunicorn_supervisor.log   ; Where to write log messages
redirect_stderr = true                                       ; Save stderr in the same log
environment=LANG=en_US.UTF-8,LC_ALL=en_US.UTF-8              ; Set UTF-8 as default encoding

upstream app_server {
    server unix:/home/urban/run/gunicorn.sock fail_timeout=0;
}

server {
    listen 80;

    # add here the ip address of your server
    # or a domain pointing to that ip (like example.com or www.example.com)
    server_name 104.236.5.15;

    keepalive_timeout 5;
    client_max_body_size 4G;

    access_log /home/urban/logs/nginx-access.log;
    error_log /home/urban/logs/nginx-error.log;

    location /static/ {
        alias /home/facundo/static/;
    }

    # checks for static file, if not found proxy to app
    location / {
        try_files $uri @proxy_to_app;
    }

    location @proxy_to_app {
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header Host $http_host;
      proxy_redirect off;
      proxy_pass http://104.236.5.15;
    }
}
