# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-11 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perros', '0002_auto_20171110_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='perro',
            name='contacto',
            field=models.CharField(default='no especificado', max_length=15),
        ),
        migrations.AlterField(
            model_name='perro',
            name='direccion',
            field=models.CharField(default='no especificado', max_length=250, verbose_name='Zona (Barrio)'),
        ),
    ]
