# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-11 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perros', '0003_auto_20171111_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='perro',
            name='encontro_casa',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='perro',
            name='direccion',
            field=models.CharField(max_length=250, verbose_name='Zona (Barrio)'),
        ),
        migrations.AlterField(
            model_name='perro',
            name='estado',
            field=models.CharField(choices=[('Excelente estado', 'EXCELENTE ESTADO'), ('Buen estado', 'BUEN ESTADO'), ('Lastimado', 'LASTIMADO'), ('Mal estado', 'MAL ESTADO')], default='buen estado', max_length=20),
        ),
        migrations.AlterField(
            model_name='perro',
            name='tamano',
            field=models.CharField(choices=[('Muy g rande', 'MUY GRANDE'), ('Grande', 'GRANDE'), ('Mediano', ' MEDIANO'), ('Chico', 'CHICO'), ('Muy chico', 'MUY CHICO')], default='mediano', max_length=15),
        ),
    ]
