# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 23:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('perros', '0007_perro_encontro_casa'),
    ]

    operations = [
        migrations.AddField(
            model_name='perro',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perro_create', to=settings.AUTH_USER_MODEL, verbose_name='author'),
        ),
        migrations.AddField(
            model_name='perro',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perro_update', to=settings.AUTH_USER_MODEL, verbose_name='last updated by'),
        ),
    ]
