# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 02:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perros', '0009_auto_20171113_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='perro',
            name='subido_por',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='perro',
            name='contacto',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='perro',
            name='edad',
            field=models.CharField(choices=[('Cachorro', 'CACHORRO'), ('Adulto', 'ADULTO')], max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='perro',
            name='sexo',
            field=models.CharField(choices=[('Macho', 'MACHO'), ('Hembra', 'HEMBRA')], max_length=5, null=True),
        ),
    ]
