# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perros', '0011_auto_20171120_0103'),
    ]

    operations = [
        migrations.AddField(
            model_name='perro',
            name='imagen',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
