# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 01:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perros', '0012_perro_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perro',
            name='subido_por',
        ),
        migrations.AlterField(
            model_name='perro',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='pics'),
        ),
    ]
