# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-26 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perros', '0014_auto_20180423_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perro',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='perros'),
        ),
    ]
