# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-26 23:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perros', '0015_auto_20180426_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='perro',
            name='aprobado',
            field=models.BooleanField(default=False),
        ),
    ]
